### ISSUE TITLE
Running demo app without CUDA crash with "couldn't find "libcublas.so""

### ISSUE THREAD

**Issue by BrianOn99** [soumith/torch-android#92]
Building torch-android with `WITH_CUDA=${WITH_CUDA:-"OFF"}` and `ARCH=${ARCH:-"v7n"}` is successful.  Then I build the demo app in `demos/android-demo`, and get a success message.  However, running the app will crash:

> D/SurfaceFlinger(  278): FPS : 9.57
W/SurfaceFlinger(  278): Fail to Open /sys/devices/platform/gpusysfs/fps
D/torchdemo(31616): Hello from JAVA
D/SurfaceFlinger(  278): FPS : 9.57
W/SurfaceFlinger(  278): Fail to Open /sys/devices/platform/gpusysfs/fps
D/AndroidRuntime(31616): Shutting down VM
E/AndroidRuntime(31616): FATAL EXCEPTION: main
E/AndroidRuntime(31616): Process: com.torch.torchdemo, PID: 31616
E/AndroidRuntime(31616): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.torch.torch
demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.torch.torchdemo-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libcubl
as.so"
E/AndroidRuntime(31616):        at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime(31616):        at java.lang.System.loadLibrary(System.java:989)
E/AndroidRuntime(31616):        at com.torch.Torch.setContext(Torch.java:23)
E/AndroidRuntime(31616):        at com.torch.torchdemo.TorchDemo.onCreate(TorchDemo.java:20)
E/AndroidRuntime(31616):        at android.app.Activity.performCreate(Activity.java:6289)
E/AndroidRuntime(31616):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime(31616):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
E/AndroidRuntime(31616):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
E/AndroidRuntime(31616):        at android.app.ActivityThread.access$900(ActivityThread.java:177)
E/AndroidRuntime(31616):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
E/AndroidRuntime(31616):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31616):        at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(31616):        at android.app.ActivityThread.main(ActivityThread.java:5951)
E/AndroidRuntime(31616):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31616):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31616):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(31616):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
V/ApplicationPolicy(  901): isApplicationStateBlocked userId 0 pkgname com.torch.torchdemo
W/ActivityManager(  901):   Force finishing activity com.torch.torchdemo/.TorchDemo

Here are files inside libs/armeabi-v7a:
> ➔ ls libs/armeabi-v7a
libTH.so             libimage.so   libnnx.so    libpng16.so    libsys.so          libtorch.so
libTHNN.so           libluaT.so    libpaths.so  libppm.so      libthreads.so      libtorchandroid.so
libgnustl_shared.so  libluajit.so  libpng.so    libsundown.so  libthreadsmain.so

What's wrong with my build?  My phone is an arm-v7. Thanks in advance.

**Comment by dneprDroid** [comment]
Maybe loading "libcublas.so" is redundant, because mobile GPUs don't support CUDA.
Can you share your **libtorchandroid.so** from *libs/armeabi-v7a* folder?

**Comment by BrianOn99** [comment]
@dneprDroid Here is the file:
https://dl.dropboxusercontent.com/u/77650107/libtorchandroid.so

**Comment by paramsen** [comment]
Hi. The demo is actually for testing/verifying CUDA, you'll have to modify it in order to work without CUDA. As you can see in [main.lua][1] it actually only tests CUDA since `cutorch` and `cunn` are CUDA libs. Also in the [Android.mk][2] some CUDA binaries are linked that need to be removed.

Here's a modified `main.lua` that simply verifies that torch can be loaded:

> require 'torch'
> print("Torch loaded")

`Android.mk` without CUDA, stripped `-lTHC -lcutorh -lTHCUNN`:

> LOCAL_PATH := $(call my-dir)
> include $(CLEAR_VARS)
> LOCAL_MODULE := torchdemo
> LOCAL_C_INCLUDES += ../../install/include
> LOCAL_SRC_FILES := torchdemo.cpp
> LOCAL_LDLIBS := -L ../../install/lib -L ../../install/libs/$(APP_ABI) -lnnx -lTHNN -ltorchandroid -llog -landroid
> include $(BUILD_SHARED_LIBRARY)

The demos should be updated, they must be pretty old since they rely on ANT and old NDK build chain. It's pretty confusing that CUDA is required as well without any notes.

[1]: https://github.com/soumith/torch-android/blob/master/demos/android-demo/assets/main.lua
[2]: https://github.com/soumith/torch-android/blob/master/demos/android-demo/jni/Android.mk

**Comment by BrianOn99** [comment]
Thanks @paramsen for your detailed explanation and clarification.  I think the README instruction is misleading if what you mention is true.
